const PLAYER_NAME_OVERRIDES: Record<string, string> = {
  "ar-agustin-giay": "阿古斯丁·吉亚伊",
  "ar-alan-varela": "阿兰·巴雷拉",
  "ar-alejandro-garnacho": "加纳乔",
  "ar-alexis-mac-allister": "麦卡利斯特",
  "ar-anibal-moreno": "阿尼瓦尔·莫雷诺",
  "ar-claudio-echeverri": "埃切维里",
  "ar-cristian-romero": "罗梅罗",
  "ar-emiliano-buendia": "布恩迪亚",
  "ar-emiliano-martinez": "埃米利亚诺·马丁内斯",
  "ar-enzo-fernandez": "恩佐",
  "ar-exequiel-palacios": "帕拉西奥斯",
  "ar-ezequiel-fernandez": "埃塞基耶尔·费尔南德斯",
  "ar-facundo-cambeses": "坎贝塞斯",
  "ar-facundo-medina": "梅迪纳",
  "ar-franco-mastantuono": "马斯坦托诺",
  "ar-german-pezzella": "佩泽拉",
  "ar-geronimo-rulli": "鲁利",
  "ar-gianluca-prestianni": "普雷斯蒂亚尼",
  "ar-giovani-lo-celso": "洛塞尔索",
  "ar-giuliano-simeone": "朱利亚诺·西蒙尼",
  "ar-gonzalo-montiel": "蒙铁尔",
  "ar-guido-rodriguez": "圭多·罗德里格斯",
  "ar-jose-manuel-lopez": "何塞·曼努埃尔·洛佩斯",
  "ar-juan-musso": "穆索",
  "ar-julian-alvarez": "阿尔瓦雷斯",
  "ar-kevin-mac-allister": "凯文·麦卡利斯特",
  "ar-lautaro-di-lollo": "劳塔罗·迪洛洛",
  "ar-lautaro-martinez": "劳塔罗",
  "ar-leandro-paredes": "帕雷德斯",
  "ar-leonardo-balerdi": "巴莱尔迪",
  "ar-lionel-messi": "梅西",
  "ar-lisandro-martinez": "利桑德罗·马丁内斯",
  "ar-lucas-martinez-quarta": "卢卡斯·马丁内斯·夸尔塔",
  "ar-marcos-senesi": "塞内西",
  "ar-mateo-pellegrino": "马特奥·佩莱格里诺",
  "ar-matias-soule": "苏莱",
  "ar-maximo-perrone": "佩罗内",
  "ar-milton-delgado": "米尔顿·德尔加多",
  "ar-nahuel-molina": "莫利纳",
  "ar-nicolas-capaldo": "卡帕尔多",
  "ar-nicolas-dominguez": "多明格斯",
  "ar-nicolas-gonzalez": "尼古拉斯·冈萨雷斯",
  "ar-nicolas-otamendi": "奥塔门迪",
  "ar-nicolas-paz": "尼科·帕斯",
  "ar-rodrigo-de-paul": "德保罗",
  "ar-santiago-beltran": "圣地亚哥·贝尔特兰",
  "ar-santiago-castro": "圣地亚哥·卡斯特罗",
  "ar-thiago-almada": "蒂亚戈·阿尔马达",
  "ar-tomas-aranda": "托马斯·阿兰达",
  "ar-walter-benitez": "沃尔特·贝尼特斯",
  "ar-zaid-romero": "扎伊德·罗梅罗",
  "at-carney-chukwuemeka": "丘库埃梅卡",
  "be-alexis-saelemaekers": "萨勒马克尔斯",
  "be-amadou-onana": "阿马杜·奥纳纳",
  "be-charles-de-ketelaere": "德凯特拉雷",
  "be-diego-moreira": "迭戈·莫雷拉",
  "be-dodi-lukebakio": "卢克巴基奥",
  "be-hans-vanaken": "瓦纳肯",
  "be-jeremy-doku": "多库",
  "be-kevin-de-bruyne": "德布劳内",
  "be-koni-de-winter": "德温特",
  "be-leandro-trossard": "特罗萨德",
  "be-matias-fernandez-pardo": "费尔南德斯-帕尔多",
  "be-maxim-de-cuyper": "德库伊珀",
  "be-mike-penders": "彭德斯",
  "be-nicolas-raskin": "拉斯金",
  "be-romelu-lukaku": "卢卡库",
  "be-senne-lammens": "拉门斯",
  "be-thibaut-courtois": "库尔图瓦",
  "be-timothy-castagne": "卡斯塔涅",
  "be-youri-tielemans": "蒂勒曼斯",
  "be-zeno-debast": "德巴斯特",
  "br-alex-sandro": "阿莱士·桑德罗",
  "br-alisson-becker": "阿利松",
  "br-bremer": "布雷默",
  "br-bruno-guimaraes": "吉马良斯",
  "br-casemiro": "卡塞米罗",
  "br-danilo": "达尼洛",
  "br-danilo-santos": "达尼洛·桑托斯",
  "br-douglas-santos": "道格拉斯·桑托斯",
  "br-ederson": "埃德森",
  "br-endrick": "恩德里克",
  "br-fabinho": "法比尼奥",
  "br-gabriel-magalhaes": "加布里埃尔·马加良斯",
  "br-gabriel-martinelli": "马丁内利",
  "br-igor-thiago": "伊戈尔·蒂亚戈",
  "br-leo-pereira": "莱奥·佩雷拉",
  "br-lucas-paqueta": "帕奎塔",
  "br-luiz-henrique": "路易斯·恩里克",
  "br-marquinhos": "马尔基尼奥斯",
  "br-matheus-cunha": "马特乌斯·库尼亚",
  "br-neymar": "内马尔",
  "br-raphinha": "拉菲尼亚",
  "br-rayan": "拉扬",
  "br-roger-ibanez": "伊巴涅斯",
  "br-vinicius-junior": "维尼修斯",
  "br-wesley": "韦斯利",
  "br-weverton": "韦弗顿",
  "ca-jonathan-david": "乔纳森·戴维",
  "ch-gregor-kobel": "科贝尔",
  "ch-manuel-akanji": "阿坎吉",
  "co-juan-camilo-hernandez": "胡安·卡米洛·埃尔南德斯",
  "co-luis-diaz": "路易斯·迪亚斯",
  "co-luis-suarez": "路易斯·苏亚雷斯",
  "de-aleksandar-pavlovic": "帕夫洛维奇",
  "de-alexander-nubel": "努贝尔",
  "de-angelo-stiller": "斯蒂勒",
  "de-antonio-rudiger": "吕迪格",
  "de-deniz-undav": "昂达夫",
  "de-felix-nmecha": "恩梅查",
  "de-florian-wirtz": "维尔茨",
  "de-jamal-musiala": "穆西亚拉",
  "de-jamie-leweling": "勒韦林",
  "de-jonathan-tah": "塔",
  "de-joshua-kimmich": "基米希",
  "de-kai-havertz": "哈弗茨",
  "de-lennart-karl": "莱纳特·卡尔",
  "de-leon-goretzka": "格雷茨卡",
  "de-leroy-sane": "萨内",
  "de-manuel-neuer": "诺伊尔",
  "de-maximilian-beier": "拜尔",
  "de-nick-woltemade": "沃尔特马德",
  "de-nico-schlotterbeck": "施洛特贝克",
  "de-oliver-baumann": "鲍曼",
  "de-waldemar-anton": "安东",
  "eg-mohamed-salah": "萨拉赫",
  "es-alex-baena": "阿莱士·巴埃纳",
  "es-alejandro-grimaldo": "格里马尔多",
  "es-aymeric-laporte": "拉波尔特",
  "es-borja-iglesias": "博尔哈·伊格莱西亚斯",
  "es-dani-olmo": "奥尔莫",
  "es-david-raya": "大卫·拉亚",
  "es-eric-garcia": "埃里克·加西亚",
  "es-fabian-ruiz": "法比安·鲁伊斯",
  "es-ferran-torres": "费兰·托雷斯",
  "es-gavi": "加维",
  "es-joan-garcia": "霍安·加西亚",
  "es-lamine-yamal": "亚马尔",
  "es-marc-cucurella": "库库雷利亚",
  "es-marc-pubill": "普比尔",
  "es-marcos-llorente": "马科斯·略伦特",
  "es-martin-zubimendi": "祖比门迪",
  "es-mikel-merino": "梅里诺",
  "es-mikel-oyarzabal": "奥亚萨瓦尔",
  "es-nico-williams": "尼科·威廉姆斯",
  "es-pau-cubarsi": "库巴西",
  "es-pedri": "佩德里",
  "es-pedro-porro": "佩德罗·波罗",
  "es-rodri": "罗德里",
  "es-unai-simon": "乌奈·西蒙",
  "es-victor-munoz": "维克托·穆尼奥斯",
  "es-yeremy-pino": "耶雷米·皮诺",
  "fr-adrien-rabiot": "拉比奥",
  "fr-aurelien-tchouameni": "楚阿梅尼",
  "fr-bradley-barcola": "巴尔科拉",
  "fr-brice-samba": "布里斯·桑巴",
  "fr-dayot-upamecano": "于帕梅卡诺",
  "fr-desire-doue": "杜埃",
  "fr-ibrahima-konate": "科纳特",
  "fr-jean-philippe-mateta": "马特塔",
  "fr-jules-kounde": "孔德",
  "fr-kylian-mbappe": "姆巴佩",
  "fr-lucas-digne": "迪涅",
  "fr-lucas-hernandez": "卢卡斯·埃尔南德斯",
  "fr-maghnes-akliouche": "阿克利乌什",
  "fr-malo-gusto": "古斯托",
  "fr-manu-kone": "科内",
  "fr-marcus-thuram": "小图拉姆",
  "fr-maxence-lacroix": "拉克鲁瓦",
  "fr-michael-olise": "奥利塞",
  "fr-mike-maignan": "迈尼昂",
  "fr-n-golo-kante": "坎特",
  "fr-ousmane-dembele": "登贝莱",
  "fr-rayan-cherki": "切尔基",
  "fr-robin-risser": "里瑟",
  "fr-theo-hernandez": "特奥·埃尔南德斯",
  "fr-warren-zaire-emery": "扎伊尔-埃梅里",
  "fr-william-saliba": "萨利巴",
  "gb-eng-anthony-gordon": "安东尼·戈登",
  "gb-eng-bukayo-saka": "萨卡",
  "gb-eng-dan-burn": "丹·伯恩",
  "gb-eng-dean-henderson": "迪恩·亨德森",
  "gb-eng-declan-rice": "赖斯",
  "gb-eng-djed-spence": "斯彭斯",
  "gb-eng-eberechi-eze": "埃泽",
  "gb-eng-elliot-anderson": "埃利奥特·安德森",
  "gb-eng-ezri-konsa": "孔萨",
  "gb-eng-harry-kane": "凯恩",
  "gb-eng-ivan-toney": "伊万·托尼",
  "gb-eng-james-trafford": "特拉福德",
  "gb-eng-jarell-quansah": "昆萨",
  "gb-eng-john-stones": "斯通斯",
  "gb-eng-jordan-henderson": "亨德森",
  "gb-eng-jordan-pickford": "皮克福德",
  "gb-eng-jude-bellingham": "贝林厄姆",
  "gb-eng-kobbie-mainoo": "梅努",
  "gb-eng-marc-guehi": "格伊",
  "gb-eng-marcus-rashford": "拉什福德",
  "gb-eng-morgan-rogers": "摩根·罗杰斯",
  "gb-eng-nico-o-reilly": "尼科·奥赖利",
  "gb-eng-noni-madueke": "马杜埃凯",
  "gb-eng-ollie-watkins": "沃特金斯",
  "gb-eng-reece-james": "里斯·詹姆斯",
  "gb-eng-tino-livramento": "利夫拉门托",
  "hr-andrej-kramaric": "克拉马里奇",
  "hr-ante-budimir": "布迪米尔",
  "hr-dominik-kotarski": "科塔尔斯基",
  "hr-dominik-livakovic": "利瓦科维奇",
  "hr-duje-caleta-car": "卡莱塔-卡尔",
  "hr-ivan-perisic": "佩里西奇",
  "hr-josip-stanisic": "斯塔尼希奇",
  "hr-josko-gvardiol": "格瓦迪奥尔",
  "hr-luka-modric": "莫德里奇",
  "hr-marco-pasalic": "马尔科·帕萨利奇",
  "hr-mario-pasalic": "马里奥·帕萨利奇",
  "hr-mateo-kovacic": "科瓦契奇",
  "hr-nikola-vlasic": "弗拉希奇",
  "hr-petar-musa": "佩塔尔·穆萨",
  "hr-petar-sucic": "苏契奇",
  "jp-koki-ogawa": "小川航基",
  "jp-wataru-endo": "远藤航",
  "kr-son-heung-min": "孙兴慜",
  "ma-achraf-hakimi": "阿什拉夫·哈基米",
  "ma-ayoub-el-kaabi": "阿尤布·卡比",
  "ma-azzedine-ounahi": "奥纳希",
  "ma-brahim-diaz": "布拉欣·迪亚斯",
  "ma-noussair-mazraoui": "马兹拉维",
  "ma-sofyan-amrabat": "阿姆拉巴特",
  "ma-soufiane-rahimi": "拉希米",
  "mx-alexis-vega": "阿莱克西斯·维加",
  "mx-edson-alvarez": "埃德森·阿尔瓦雷斯",
  "mx-german-berterame": "贝尔特拉梅",
  "mx-santiago-gimenez": "圣地亚哥·希门尼斯",
  "nl-bart-verbruggen": "费尔布鲁亨",
  "nl-brian-brobbey": "布罗贝",
  "nl-cody-gakpo": "加克波",
  "nl-crysencio-summerville": "萨默维尔",
  "nl-denzel-dumfries": "邓弗里斯",
  "nl-donyell-malen": "马伦",
  "nl-frenkie-de-jong": "弗朗基·德容",
  "nl-guus-til": "古斯·蒂尔",
  "nl-jan-paul-van-hecke": "扬·保罗·范赫克",
  "nl-jorrel-hato": "哈托",
  "nl-jurrien-timber": "廷贝尔",
  "nl-justin-kluivert": "小克鲁伊维特",
  "nl-mark-flekken": "弗莱肯",
  "nl-marten-de-roon": "德容恩",
  "nl-mats-wieffer": "韦弗",
  "nl-memphis-depay": "德佩",
  "nl-micky-van-de-ven": "范德芬",
  "nl-nathan-ake": "阿克",
  "nl-noa-lang": "诺亚·朗",
  "nl-quinten-timber": "昆滕·廷贝尔",
  "nl-robin-roefs": "鲁夫斯",
  "nl-ryan-gravenberch": "赫拉芬贝赫",
  "nl-teun-koopmeiners": "库普梅纳斯",
  "nl-tijjani-reijnders": "赖因德斯",
  "nl-virgil-van-dijk": "范戴克",
  "nl-wout-weghorst": "韦霍斯特",
  "no-alexander-s-rloth": "索尔洛特",
  "no-erling-haaland": "哈兰德",
  "no-martin-degaard": "厄德高",
  "no-oscar-bobb": "奥斯卡·鲍勃",
  "pt-bernardo-silva": "B席",
  "pt-bruno-fernandes": "B费",
  "pt-cristiano-ronaldo": "C罗",
  "pt-diogo-costa": "迪奥戈·科斯塔",
  "pt-diogo-dalot": "达洛特",
  "pt-francisco-conceicao": "小孔塞桑",
  "pt-francisco-trincao": "特林康",
  "pt-goncalo-guedes": "格德斯",
  "pt-goncalo-inacio": "伊纳西奥",
  "pt-goncalo-ramos": "贡萨洛·拉莫斯",
  "pt-joao-cancelo": "坎塞洛",
  "pt-joao-felix": "菲利克斯",
  "pt-joao-neves": "若昂·内维斯",
  "pt-jose-sa": "若泽·萨",
  "pt-matheus-nunes": "马特乌斯·努内斯",
  "pt-nelson-semedo": "塞梅多",
  "pt-nuno-mendes": "努诺·门德斯",
  "pt-pedro-neto": "佩德罗·内托",
  "pt-rafael-leao": "莱奥",
  "pt-renato-veiga": "维加",
  "pt-ricardo-velho": "里卡多·韦略",
  "pt-ruben-dias": "鲁本·迪亚斯",
  "pt-ruben-neves": "鲁本·内维斯",
  "pt-rui-silva": "鲁伊·席尔瓦",
  "pt-samu-costa": "萨穆·科斯塔",
  "pt-vitinha": "维蒂尼亚",
  "se-alexander-isak": "伊萨克",
  "se-viktor-gyokeres": "约克雷斯",
  "sn-ibrahim-mbaye": "易卜拉欣·姆巴耶",
  "sn-nicolas-jackson": "尼古拉斯·杰克逊",
  "tr-altay-bay-nd-r": "阿尔泰·巴因迪尔",
  "tr-hakan-calhanoglu": "恰尔汗奥卢",
  "tr-kenan-y-ld-z": "凯南·伊尔迪兹",
  "tr-salih-ozcan": "萨利赫·厄兹詹",
  "us-christian-pulisic": "普利西奇",
  "us-weston-mckennie": "麦肯尼",
  "uy-darwin-nunez": "努涅斯",
  "uy-federico-valverde": "巴尔韦德",
  "uy-federico-vinas": "维尼亚斯",
  "uy-jose-maria-gimenez": "希门尼斯",
  "uy-manuel-ugarte": "乌加特",
  "uy-mathias-olivera": "奥利维拉",
  "uy-rodrigo-aguirre": "罗德里戈·阿吉雷",
  "uy-rodrigo-bentancur": "本坦库尔",
  "uy-ronald-araujo": "阿劳霍",
  "uy-sergio-rochet": "罗切特",
};

const WORD_OVERRIDES: Record<string, string> = {
  achraf: "阿什拉夫",
  adam: "亚当",
  adrian: "阿德里安",
  alejandro: "亚历杭德罗",
  alex: "阿莱士",
  alexander: "亚历山大",
  alexis: "阿莱克西斯",
  ali: "阿里",
  alisson: "阿利松",
  amadou: "阿马杜",
  anderson: "安德森",
  andre: "安德烈",
  angel: "安赫尔",
  anthony: "安东尼",
  antonio: "安东尼奥",
  arthur: "阿图尔",
  ayoub: "阿尤布",
  ben: "本",
  benjamin: "本杰明",
  bernardo: "贝尔纳多",
  bradley: "布拉德利",
  brian: "布莱恩",
  bruno: "布鲁诺",
  camilo: "卡米洛",
  carlos: "卡洛斯",
  christian: "克里斯蒂安",
  cristian: "克里斯蒂安",
  daniel: "丹尼尔",
  dani: "达尼",
  david: "大卫",
  diego: "迭戈",
  diogo: "迪奥戈",
  ederson: "埃德森",
  emiliano: "埃米利亚诺",
  enzo: "恩佐",
  eric: "埃里克",
  fabian: "法比安",
  facundo: "法昆多",
  federico: "费德里科",
  felix: "费利克斯",
  fernandez: "费尔南德斯",
  fernando: "费尔南多",
  franco: "弗朗科",
  francisco: "弗朗西斯科",
  gabriel: "加布里埃尔",
  german: "赫尔曼",
  giovanni: "乔瓦尼",
  gonzalo: "冈萨洛",
  harry: "哈里",
  hector: "埃克托",
  ibrahima: "易卜拉希马",
  ivan: "伊万",
  james: "詹姆斯",
  joao: "若昂",
  jonathan: "乔纳森",
  jose: "何塞",
  juan: "胡安",
  julian: "胡利安",
  kevin: "凯文",
  leo: "莱奥",
  leonardo: "莱昂纳多",
  lucas: "卢卡斯",
  luis: "路易斯",
  manuel: "曼努埃尔",
  marc: "马克",
  marco: "马尔科",
  marcos: "马科斯",
  mario: "马里奥",
  martin: "马丁",
  mateo: "马特奥",
  matheus: "马特乌斯",
  maxim: "马克西姆",
  michael: "迈克尔",
  mike: "迈克",
  nicolas: "尼古拉斯",
  nico: "尼科",
  patrick: "帕特里克",
  paul: "保罗",
  pedro: "佩德罗",
  rafael: "拉斐尔",
  ricardo: "里卡多",
  robert: "罗伯特",
  robin: "罗宾",
  rodrigo: "罗德里戈",
  ryan: "瑞安",
  santiago: "圣地亚哥",
  sergio: "塞尔吉奥",
  thiago: "蒂亚戈",
  thomas: "托马斯",
  timothy: "蒂莫西",
  tomas: "托马斯",
  victor: "维克托",
  walter: "沃尔特",
  wesley: "韦斯利",
};

const LETTER_OVERRIDES: Record<string, string> = {
  a: "阿",
  b: "布",
  c: "克",
  d: "德",
  e: "埃",
  f: "夫",
  g: "格",
  h: "赫",
  i: "伊",
  j: "杰",
  k: "克",
  l: "尔",
  m: "姆",
  n: "恩",
  o: "奥",
  p: "普",
  q: "库",
  r: "尔",
  s: "斯",
  t: "特",
  u: "乌",
  v: "维",
  w: "韦",
  x: "克斯",
  y: "伊",
  z: "兹",
};

const CHUNK_OVERRIDES: [string, string][] = [
  ["sch", "施"],
  ["tch", "奇"],
  ["ch", "奇"],
  ["sh", "什"],
  ["th", "特"],
  ["ph", "夫"],
  ["ck", "克"],
  ["qu", "夸"],
  ["gh", "格"],
  ["gn", "尼"],
  ["ll", "利"],
  ["rr", "尔"],
  ["ng", "恩"],
  ["ae", "埃"],
  ["ai", "艾"],
  ["ay", "艾"],
  ["au", "奥"],
  ["ea", "伊"],
  ["ee", "伊"],
  ["ei", "埃"],
  ["eu", "尤"],
  ["ey", "埃"],
  ["ie", "耶"],
  ["oa", "奥"],
  ["oe", "厄"],
  ["oi", "奥伊"],
  ["oo", "乌"],
  ["ou", "乌"],
];

export function chinesePlayerName(player: { id: string; name: string; zh?: string }): string {
  const override = PLAYER_NAME_OVERRIDES[player.id];
  if (override) return override;
  if (player.zh && player.zh !== player.name && hasChinese(player.zh)) return player.zh;
  return transliterateName(player.name);
}

function transliterateName(name: string): string {
  const parts = name
    .split(/[\s\-.'’]+/)
    .map((part) => transliterateWord(part))
    .filter(Boolean);
  return parts.length ? parts.join("·") : name;
}

function transliterateWord(word: string): string {
  const normalized = normalizeLatin(word);
  if (!normalized) return "";
  const exact = WORD_OVERRIDES[normalized];
  if (exact) return exact;

  let out = "";
  let i = 0;
  while (i < normalized.length) {
    const chunk = CHUNK_OVERRIDES.find(([key]) => normalized.startsWith(key, i));
    if (chunk) {
      out += chunk[1];
      i += chunk[0].length;
      continue;
    }
    out += LETTER_OVERRIDES[normalized[i]] ?? normalized[i];
    i += 1;
  }
  return compactTransliteration(out);
}

function normalizeLatin(value: string): string {
  return value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/æ/g, "ae")
    .replace(/ø/g, "o")
    .replace(/œ/g, "oe")
    .replace(/ß/g, "ss")
    .replace(/ł/g, "l")
    .replace(/ð/g, "d")
    .replace(/þ/g, "th")
    .replace(/[^a-z]/g, "");
}

function compactTransliteration(value: string): string {
  return value.replace(/([阿埃伊奥乌])\1+/g, "$1").replace(/(尔)\1+/g, "$1");
}

function hasChinese(value: string): boolean {
  return /[\u4e00-\u9fff]/.test(value);
}
